name: Run-Scripts
on:
  push:
    paths:
      - 'doc/generate_ID_list'
  pull_request:
    paths:
      - 'doc/generate_ID_list'

defaults:
  run:
    working-directory: ./doc

jobs:
  Run-Scripts:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Update ID list
      run: ./generate_ID_list
    
    - uses: stefanzweifel/git-auto-commit-action@v7.2.0
      with:
        commit_message: "Updated ID list."